import os
import base64

export_file = "STYLE_GUIDE.md"

part1 = """IyBDb2RlIFN0eWxlIEd1aWRlCgojIyBQeXRob24KCiMjIyBGb3JtYXR0aW5nCi0gKipG
b3JtYXR0ZXIqKjogQmxhY2sgKGxpbmUgbGVuZ3RoOiAxMDApCi0gKipJbXBvcnQgU29y
dGVyKio6IGlzb3J0IChCbGFjay1jb21wYXRpYmxlIHByb2ZpbGUpCi0gKipMaW50ZXIq
KjogZmxha2U4CgojIyMgQ29udmVudGlvbnMKLSBVc2UgZG91YmxlIHF1b3RlcyBmb3Ig
c3RyaW5ncwotIDQgc3BhY2VzIGZvciBpbmRlbnRhdGlvbiAobm8gdGFicykKLSAyIGJs
YW5rIGxpbmVzIGJldHdlZW4gdG9wLWxldmVsIGZ1bmN0aW9ucy9jbGFzc2VzCi0gMSBi
bGFuayBsaW5lIGJldHdlZW4gbWV0aG9kcyBpbiBhIGNsYXNzCi0gTWF4aW11bSBsaW5l
IGxlbmd0aDogMTAwIGNoYXJhY3RlcnMKCiMjIyBOYW1pbmcKLSBgc25ha2VfY2FzZWAg
Zm9yIGZ1bmN0aW9ucyBhbmQgdmFyaWFibGVzCi0gYFBhc2NhbENhc2VgIGZvciBjbGFz
c2VzCi0gYFVQUEVSX0NBU0VgIGZvciBjb25zdGFudHMKLSBQcmVmaXggcHJpdmF0ZSBt
ZXRob2RzIHdpdGggYF9gCgojIyMgSW1wb3J0cwpgYGBweXRob24KIyBTdGFuZGFyZCBs
aWJyYXJ5CmltcG9ydCBvcwppbXBvcnQgc3lzCgojIFRoaXJkLXBhcnR5CmZyb20gZmFz
dGFwaSBpbXBvcnQgRmFzdEFQSQpmcm9tIHNxbGFsY2hlbXkgaW1wb3J0IHRleHQKCiMg
TG9jYWwKZnJvbSBzZXJ2aWNlcy5kYl9zZXJ2aWNlIGltcG9ydCBEYXRhYmFzZU1hbmFn
ZXIKZnJvbSB1dGlscy5sb2dnZXIgaW1wb3J0IGdldF9sb2dnZXIKYGBgCgojIyMgRG9j
c3RyaW5ncwpgYGBweXRob24KZGVmIGZ1bmN0aW9uKHBhcmFtMTogc3RyLCBwYXJhbTI6
IGludCkgLT4gYm9vbDoKICAgICIiIgogICAgQnJpZWYgZGVzY3JpcHRpb24uCiAgICAK
ICAgIEFyZ3M6CiAgICAgICAgcGFyYW0xOiBEZXNjcmlwdGlvbiBvZiBwYXJhbTEKICAg
ICAgICBwYXJhbTI6IERlc2NyaXB0aW9uIG9mIHBhcmFtMgogICAgCiAgICBSZXR1cm5z
OgogICAgICAgIERlc2NyaXB0aW9uIG9mIHJldHVybiB2YWx1ZQogICAgIiIiCiAgICBw
YXNzCmBgYAoKIyMgSmF2YVNjcmlwdAoKIyMjIEZvcm1hdHRpbmcKLSAqKkZvcm1hdHRl
cioqOiBQcmV0dGllcgotICoqTGluZSBsZW5ndGgqKjogMTAwIGNoYXJhY3RlcnMKLSAq
KkluZGVudGF0aW9uKio6IDQgc3BhY2VzCi0gKipRdW90ZXMqKjogU2luZ2xlIHF1b3Rl
cwotICoqU2VtaWNvbG9ucyoqOiBZZXMKCiMjIyBDb252ZW50aW9ucwotIFVzZSBgY29u
c3RgIGFuZCBgbGV0YCwgYXZvaWQgYHZhcmAKLSBVc2UgYXJyb3cgZnVuY3Rpb25zIGZv
ciBjYWxsYmFja3MKLSBVc2UgdGVtcGxhdGUgbGl0ZXJhbHMgZm9yIHN0cmluZyBpbnRl
cnBvbGF0aW9uCi0gVXNlIGFzeW5jL2F3YWl0IGluc3RlYWQgb2YgcHJvbWlzZXMKCiMj
IyBOYW1pbmcKLSBgY2FtZWxDYXNlYCBmb3IgZnVuY3Rpb25zIGFuZCB2YXJpYWJsZXMK
LSBgUGFzY2FsQ2FzZWAgZm9yIGNsYXNzZXMKLSBgVVBQRVJfQ0FTRWAgZm9yIGNvbnN0
YW50cwoKIyMjIEV4YW1wbGUKYGBgamF2YXNjcmlwdApjb25zdCBBUElfQkFTRV9VUkwg
PSAnL2FwaS92MSc7CgpjbGFzcyBKb2JzQ29tcG9uZW50IHsKICAgIGNvbnN0cnVjdG9y
KCkgewogICAgICAgIHRoaXMuam9icyA9IFtdOwogICAgfQogICAgCiAgICBhc3luYyBs
b2FkSm9icygpIHsKICAgICAgICBjb25zdCByZXNwb25zZSA9IGF3YWl0IGZldGNoKGAk
e0FQSV9CQVNFX1VSTH0vam9ic2ApOwogICAgICAgIHJldHVybiBhd2FpdCByZXNwb25z
ZS5qc29uKCk7CiAgICB9Cn0KYGBgCg=="""
part2 = """IyMgQ1NTCgojIyMgRm9ybWF0dGluZwotICoqRm9ybWF0dGVyKio6IFByZXR0aWVyCi0g
KipJbmRlbnRhdGlvbioqOiA0IHNwYWNlcwoKIyMjIENvbnZlbnRpb25zCi0gVXNlIGtl
YmFiLWNhc2UgZm9yIGNsYXNzIG5hbWVzCi0gVXNlIENTUyB2YXJpYWJsZXMgZm9yIGNv
bG9ycyBhbmQgc3BhY2luZwotIEdyb3VwIHJlbGF0ZWQgcHJvcGVydGllcwotIE1vYmls
ZS1maXJzdCByZXNwb25zaXZlIGRlc2lnbgoKIyMjIEV4YW1wbGUKYGBgY3NzCi5qb2It
bGlzdC1pdGVtIHsKICAgIC8qIExheW91dCAqLwogICAgZGlzcGxheTogZmxleDsKICAg
IHBhZGRpbmc6IHZhcigtLXNwYWNpbmctbWQpOwogICAgCiAgICAvKiBWaXN1YWwgKi8K
ICAgIGJhY2tncm91bmQ6IHZhcigtLWNvbG9yLXN1cmZhY2UpOwogICAgYm9yZGVyOiAx
cHggc29saWQgdmFyKC0tY29sb3ItYm9yZGVyKTsKICAgIGJvcmRlci1yYWRpdXM6IHZh
cigtLXJhZGl1cy1tZCk7CiAgICAKICAgIC8qIEFuaW1hdGlvbiAqLwogICAgdHJhbnNp
dGlvbjogYWxsIDAuM3MgZWFzZTsKfQpgYGAKCiMjIEdpdCBDb21taXRzCgojIyMgRm9y
bWF0CmBgYAo8dHlwZT4oPHNjb3BlPik6IDxzdWJqZWN0PgoKPGJvZHk+Cgo8Zm9vdGVy
PgpgYGAKCiMjIyBUeXBlcwotIGBmZWF0YDogTmV3IGZlYXR1cmUKLSBgZml4YDogQnVn
IGZpeAotIGBkb2NzYDogRG9jdW1lbnRhdGlvbgotIGBzdHlsZWA6IENvZGUgc3R5bGUg
KGZvcm1hdHRpbmcsIGV0Yy4pCi0gYHJlZmFjdG9yYDogQ29kZSByZWZhY3RvcmluZwot
IGB0ZXN0YDogVGVzdHMKLSBgY2hvcmVgOiBNYWludGVuYW5jZQoKIyMjIEV4YW1wbGVz
CmBgYApmZWF0KGpvYnMpOiBhZGQgcmV0cnkgZnVuY3Rpb25hbGl0eSBmb3IgZmFpbGVk
IGpvYnMKCmZpeChwYXJzZXIpOiBoYW5kbGUgZW1wdHkgTUlCIGZpbGVzIGdyYWNlZnVs
bHkKCmRvY3MocmVhZG1lKTogdXBkYXRlIGluc3RhbGxhdGlvbiBpbnN0cnVjdGlvbnMK
CnN0eWxlOiBhcHBseSBCbGFjayBmb3JtYXR0aW5nIHRvIGFsbCBQeXRob24gZmlsZXMK
YGBgCgojIyBUb29scwoKIyMjIEZvcm1hdCBDb2RlCmBgYGJhc2gKIyBQeXRob24KYmxh
Y2sgYmFja2VuZC8gY29yZS8gc2VydmljZXMvIHV0aWxzLwppc29ydCBiYWNrZW5kLyBj
b3JlLyBzZXJ2aWNlcy8gdXRpbHMvCgojIEphdmFTY3JpcHQvQ1NTCm5weCBwcmV0dGll
ciAtLXdyaXRlICJmcm9udGVuZC8qKi8qLntqcyxjc3N9IgoKIyBBbGwgYXQgb25jZQou
L3NjcmlwdHMvZm9ybWF0X2NvZGUuc2gKYGBgCgojIyMgQ2hlY2sgU3R5bGUKYGBgYmFz
aAojIFB5dGhvbgpmbGFrZTggYmFja2VuZC8gY29yZS8gc2VydmljZXMvIHV0aWxzLwoK
IyBKYXZhU2NyaXB0Cm5weCBwcmV0dGllciAtLWNoZWNrICJmcm9udGVuZC8qKi8qLntq
cyxjc3N9IgpgYGAK"""
part3 = """
"""
part4 = """
"""

# Combine all parts (paste them here)
all_parts = [part1, part2]


# Check if file exists
if os.path.exists(export_file):
    response = input(f"⚠️ Warning: '{export_file}' already exists. Do you want to overwrite it? (y/n): ")
    if response.lower() != 'y':
        print("Operation cancelled by user.")
        exit()
    else:
        os.remove(export_file)
        print(f"Old file '{export_file}' deleted.")


for part in all_parts:
    # Decode and save
    decoded = base64.b64decode(part).decode('utf-8')
    with open(export_file, 'a', encoding='utf-8') as f:
        f.write(decoded + '\n')
    print ()
    
print(f"{export_file} created successfully!")
